name: usaficity
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cloud_firestore: ^5.2.1
  cupertino_icons: ^1.0.2
  device_info_plus: ^10.1.2
  easy_localization: ^3.0.4
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  firebase_storage: ^12.1.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_polyline_points: ^2.0.0
  gap: ^3.0.1
  geolocator: ^12.0.0
  go_router: ^14.2.3
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.2.8
  google_sign_in: ^6.2.1
  icons_plus: ^5.0.0
  image_picker: ^1.0.7
  intl: 0.19.0
  list_wheel_scroll_view_nls: ^0.0.3

  provider: any
  shared_preferences: ^2.2.2
  table_calendar: ^3.0.9

dev_dependencies:
  change_app_package_name: ^1.3.0
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launcher_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/launcher_icon.png"
    background_color: "#ed9542"
    theme_color: "#ed9542"
  windows:
    generate: true
    image_path: "assets/images/launcher_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/launcher_icon.png"
    
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
